# Generated by Django 6.0 on 2025-12-11 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squadra', models.CharField(max_length=100, verbose_name='Squadra')),
                ('giocatore', models.CharField(max_length=100, verbose_name='Giocatore')),
                ('anno_stagione', models.CharField(max_length=20, verbose_name='Stagione/Anno')),
                ('foto', models.ImageField(upload_to='maglie_foto/', verbose_name='Foto della Maglia')),
                ('dettagli_acquisto', models.TextField(blank=True, null=True, verbose_name='Dettagli Acquisto (Dove, Quando, Prezzo Pagato)')),
                ('valore_stimato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valore Stimato (€)')),
                ('note_personali', models.TextField(blank=True, null=True, verbose_name='Note e Storia Personale della Maglia')),
                ('visibile_in_vetrina', models.BooleanField(default=False, verbose_name='Mostra in Vetrina Pubblica')),
                ('fonte_esterna_info', models.TextField(blank=True, null=True, verbose_name='Informazioni Salienti (Funzione Plus)')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maglia Sportiva',
                'verbose_name_plural': 'Maglie Sportive',
            },
        ),
    ]
