# Generated by Django 6.0 on 2025-12-19 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20251212_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='maglia',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
